blank_issues_enabled: false
contact_links:
  - name: Discord
    url: soon
    about: Join Discord server for support and other.
  - name: Wiki
    url: soon
    about: Check out wiki before creating discussions.