name: Publish Release

on:
  workflow_dispatch:

jobs:
  build_release:
    name: Build and Release
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'adopt'
    - name: Gradle Wrapper Validation
      uses: gradle/actions/wrapper-validation@v4
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v4
    - name: Build with Gradle
      run: ./gradlew shadowJar
    - name: Get App Version
      id: get_version
      run: echo "version=$(./gradlew printVersion --console=plain -q --warning-mode=none)" >> $GITHUB_ENV
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: Package
        path: |
          ./build/libs/VOTL-*
        overwrite: true
    - name: Create Release
      # You may pin to the exact commit or the version.
      uses: ncipollo/release-action@v1
      with:
        allowUpdates: true
        # An optional set of paths representing artifacts to upload to the release. This may be a single path or a comma delimited list of paths (or globs)
        artifacts: ./build/libs/VOTL-*.jar
        artifactContentType: "raw"
        # Generate release notes. There needs to be a previous version for it to diff against.
        generateReleaseNotes: true
        # Optionally marks this release as prerelease. Set to true to enable.
        prerelease: (contains( ${{ env.version }} , 'SNAPSHOT'))
        # Indicates if existing release artifacts should be replaced. Defaults to true.
        replacesArtifacts: true
        # An optional tag for the release. If this is omitted the git ref will be used (if it is a tag).
        tag: ${{ env.version }}
        # The GitHub token.
        token: ${{ secrets.TOKEN }}
